#!/usr/bin/env bash
# Prints "Best School" to  display in 10 iterations
# at index 4 prints "bad luck"
# at index 8 prints "good luck"

i=1
while [ $i -le 10 ];
do
    if [ $i -eq 4 ]
    then
       echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo  "Best School"
    fi
    ((i++))
done
